name: covidtracer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  curved_navigation_bar: ^0.3.2
  fluttertoast: ^4.0.1
  dots_indicator: ^1.1.0
  http: ^0.12.0+4
  get_it: ^4.0.1
  flutter_blue: ^0.7.2
  path_provider: ^1.6.7
  flutter_bluetooth_serial: ^0.2.2
  device_info: ^0.4.2+2
  sqflite: ^1.3.0
  intl: ^0.16.1
  url_launcher: ^5.4.5
  flutter_verification_code: ^0.2.0
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
  - images/
 

  